name: verify-examples
on: [push]
jobs:
  run-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run examples
        run: |
          python examples/emceefit.py
          python examples/h2opr.py
          python examples/mapfitting.py
          python examples/modelset.py
          python examples/singlepixelfitting.py
